version: '3'
services:
  app:
    image: nginx:1.10
    container_name: weatherpoker_app
    restart: always
    working_dir: /usr/share/nginx/html
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - 8080:80